export const PAYMENT_METHODS = [
  { value: 'bkash', label: 'bKash' },
  { value: 'nagad', label: 'Nagad' },
  { value: 'rocket', label: 'Rocket' },
  { value: 'cash', label: 'Cash' },
];

export const BANKS = [
  'AB Bank PLC',
  'Al-Arafah Islami Bank PLC',
  'Bangladesh Commerce Bank Limited',
  'Bank Asia PLC',
  'Bengal Commercial Bank PLC',
  'BRAC Bank PLC',
  'Citizens Bank PLC',
  'City Bank PLC',
  'Community Bank Bangladesh PLC',
  'Dhaka Bank PLC',
  'Dutch-Bangla Bank PLC',
  'Eastern Bank PLC',
  'ICB Islamic Bank PLC',
  'IFIC Bank PLC',
  'Islami Bank Bangladesh PLC',
  'Jamuna Bank PLC',
  'Meghna Bank PLC',
  'Mercantile Bank PLC',
  'Midland Bank PLC',
  'Modhumoti Bank PLC',
  'Mutual Trust Bank PLC',
  'National Bank PLC',
  'National Credit & Commerce Bank PLC',
  'NRB Bank PLC',
  'NRBC Bank PLC',
  'ONE Bank PLC',
  'Padma Bank PLC',
  'Prime Bank PLC',
  'Pubali Bank PLC',
  'SBAC Bank PLC',
  'Shahjalal Islami Bank PLC',
  'Shimanto Bank PLC',
  'Southeast Bank PLC',
  'Standard Bank PLC',
  'The Premier Bank PLC',
  'Trust Bank PLC',
  'United Commercial Bank PLC',
  'Uttara Bank PLC',
];
